### ISSUE TITLE
BetterVolume crashing the app after 1.8.3 update

### ISSUE THREAD

**Issue by KuchiSofts** [Zerthox/BetterDiscord-Plugins#133]
when you right click on user discord will crash

**Comment by Zerthox** [comment]
This is an issue on BetterDiscord's side caused by a silent Discord update. The plugin relies on BD's ContextMenu API, which broke after the update. Already being worked on: https://github.com/BetterDiscord/BetterDiscord/commit/d2594463c061bc25f90636bb02ae587a47afd4c1 https://github.com/BetterDiscord/BetterDiscord/commit/5b8a173aa0a718f21b8403c84827de3df8d95818

Leaving this open until BD releases a fix.

**Comment by leonglo** [comment]
Same issue with BetterFolders Plugin

**Comment by Zerthox** [comment]
BetterFolders does not make use of the ContextMenu API. If you are experiencing crashes with BetterFolders, please open another issue.

**Comment by leonglo** [comment]
Nvm, that was a BD issue, they fixed it in v. 1.8.4

**Comment by Zerthox** [comment]
Fixed with BD v1.8.4. Closing.

**Comment by JuniorGenius** [comment]
This issue seems to be back.
BD 1.8.4
Discord PTB 177348 (8348aec)

**Comment by JuniorGenius** [comment]
> > This issue seems to be back. BD 1.8.4 Discord PTB 177348 (8348aec)
> 
> BD 1.8.4 Stable 177051 (becd31e) And its not crashing .. Try to use the experimental version https://gist.github.com/Zerthox/d51daa11afb7682ba9ca7cdd190bf928

I am using the experimental version, I should have specified. I believe the issue is back due to a new Discord PTB update that probably hasn't reached Stable Discord yet
