### ISSUE TITLE
crashes on canary

### ISSUE THREAD

**Issue by bobkinect98** [Zerthox/BetterDiscord-Plugins#40]
soon as i turn on the plugin its a instant crash, please fix
im on canary

**Comment by Zerthox** [comment]
Could you please specify which plugin you are talking about?

If it is BetterFolders, make sure you are on the most recent version. A crash related to a Discord update has been fixed with v2.2.3 in https://github.com/Zerthox/BetterDiscord-Plugins/commit/6140126673d22831854522c12889ae9e0c273edb.

**Comment by crzyc** [comment]
I downloaded v2.2.3 of BetterFolders on latest Discord stable, and it still crashes. Might be related to this same bug. I know for certain that BetterFolders is the cause of the crash because removing it from my plugins folder makes Discord run as usual.

**Comment by Zerthox** [comment]
Please check for error messages in the console. A clean install of BD with BetterFolders v2.2.3 runs completely fine on my machine.

**Comment by Anach** [comment]
It's fine in PTB with 2.2.3, but crashing with 2.2.3 in PTB running BD beta, so that might be why there's different reports.

**Comment by Zerthox** [comment]
Closing due to inactivity.
